# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 17:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_auto_20180315_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
