# Generated by Django 2.2.19 on 2021-03-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_auto_20200902_1545'),
        ('resumes', '0006_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industries.Industry'),
        ),
    ]
