# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 15:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180718_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='google_profile',
        ),
    ]
