# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-16 00:05


import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0002_auto_20180315_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogcolor',
            name='rgb_color',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
