# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-26 17:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0003_auto_20180316_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
