# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-06 14:18


import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('event_logs', '0004_auto_20190926_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogcolor',
            name='rgb_color',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
