# Generated by Django 2.2.22 on 2021-05-25 12:50

from django.db import migrations
import tendenci.apps.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_auto_20210525_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='slug',
            field=tendenci.apps.base.fields.SlugField(db_index=True, max_length=100, unique=True, verbose_name='URL Path'),
        ),
    ]
