# Generated by Django 3.2.12 on 2023-01-01 13:40

from django.db import migrations

def update_officers_group_perms(apps, schema_editor):
    from tendenci.apps.committees.models import Committee
    #Committee = apps.get_model("committees", "Committee")
    for committee in Committee.objects.all():
        committee.update_group_perms()


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0009_committee_featured_image'),
    ]

    operations = [
        migrations.RunPython(update_officers_group_perms),
    ]
