# Generated by Django 2.2.14 on 2020-08-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0012_auto_20200731_1736'),
        ('corporate_memberships', '0016_auto_20180315_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpprofile',
            name='directory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directories.Directory'),
        ),
    ]
