# Generated by Django 2.2.15 on 2020-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0018_auto_20200805_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpmembershipapp',
            name='donation_default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Default Amount'),
        ),
        migrations.AddField(
            model_name='corpmembershipapp',
            name='donation_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Donation on Renewal'),
        ),
        migrations.AddField(
            model_name='corpmembershipapp',
            name='donation_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label'),
        ),
    ]
