# Generated by Django 2.2.16 on 2020-09-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0021_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpprofile',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='phone2'),
        ),
    ]
