# Generated by Django 2.2.16 on 2020-10-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0022_corpprofile_phone2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpmembership',
            options={'permissions': (('approve_corpmembership', 'Can approve corporate memberships'),), 'verbose_name': 'Corporate Membership', 'verbose_name_plural': 'Corporate Memberships'},
        ),
    ]
