# Generated by Django 2.2.16 on 2020-10-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0023_auto_20201005_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatemembershiptype',
            name='require_approval',
            field=models.CharField(choices=[('for_all', 'for ALL (Paid & Non-Paid)'), ('for_non_paid_only', 'for Non-Paid Only')], default='for_non_paid_only', max_length=20, verbose_name='Require Approval'),
        ),
    ]
