# Generated by Django 3.2.16 on 2023-02-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0026_auto_20221123_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('zip', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, default='', max_length=50, verbose_name='Fax')),
                ('corp_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='corporate_memberships.corpprofile')),
            ],
        ),
    ]
