# Generated by Django 3.2.23 on 2024-04-11 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20240409_1733'),
        ('entities', '0005_entity_show_for_donation'),
        ('corporate_memberships', '0029_broadcastemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpmembership',
            name='donate_to_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity'),
        ),
        migrations.AddField(
            model_name='corpmembership',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donation'),
        ),
    ]
