# Generated by Django 4.2.14 on 2024-08-29 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_region_invoice_footer_region_invoice_header'),
        ('corporate_memberships', '0030_auto_20240411_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='region',
            field=models.ForeignKey(blank=True, help_text='If a region is selected, the notice will go out to members in this region. <br />Skip the next field "Regions to exclude" if this field is selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp_notices', to='regions.region'),
        ),
        migrations.AddField(
            model_name='notice',
            name='regions_to_exclude',
            field=models.ManyToManyField(blank=True, help_text="Select regions you want to exclude so that members in those regions won't receive this notice.", related_name='corp_notices_excluded', to='regions.region'),
        ),
    ]
