# Generated by Django 4.2.21 on 2025-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0033_auto_20250506_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpprofile',
            name='ud19',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud20',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud21',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud22',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud23',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud24',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud25',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud26',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud27',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud28',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud29',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud30',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud31',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud32',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud33',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud34',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud35',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud36',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud37',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='corpprofile',
            name='ud38',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
