# Generated by Django 4.2.21 on 2025-06-10 16:56

from django.db import migrations

def add_ud_to_existing_apps(apps, schema_editor):
    CorpMembershipApp = apps.get_model('corporate_memberships', 'CorpMembershipApp')
    CorpMembershipAppField = apps.get_model('corporate_memberships', 'CorpMembershipAppField')
    field_names = ['ud19', 'ud20', 'ud21', 'ud22', 'ud23', 'ud24', 'ud25', 'ud26', 'ud27', 'ud28',
                   'ud29', 'ud30', 'ud31', 'ud32', 'ud33', 'ud34', 'ud35', 'ud36', 'ud37', 'ud38']
    corp_apps = CorpMembershipApp.objects.all()
    position = 60
    for corp_app in corp_apps:
        for field_name in field_names:
            if not CorpMembershipAppField.objects.filter(corp_app=corp_app, field_name=field_name).exists():
                app_field = CorpMembershipAppField(
                             corp_app=corp_app,
                             label=field_name,
                             field_name=field_name,
                             position=position,
                             display=False,)
                app_field.save()
                position += 1


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0034_corpprofile_ud19_corpprofile_ud20_corpprofile_ud21_and_more'),
    ]

    operations = [
        migrations.RunPython(add_ud_to_existing_apps),
    ]
