# Generated by Django 4.2.21 on 2025-10-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0035_auto_20250610_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpmembership',
            name='above_cap_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='corpmembership',
            name='corp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='corpmembership',
            name='num_ind_above_cap',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
