# Generated by Django 3.2.16 on 2023-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnPushedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(null=True)),
                ('event_id', models.PositiveIntegerField(null=True)),
                ('identifier', models.CharField(max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
