# Generated by Django 2.2.24 on 2021-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
