# Generated by Django 3.2.18 on 2023-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20230421_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
