# Generated by Django 5.2.17 on 2026-09-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_refund_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
