# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 15:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180315_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='google_profile',
        ),
    ]
