# Generated by Django 2.2.24 on 2021-06-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20200902_1545'),
        ('chapters', '0006_officer_expire_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='state'),
        ),
    ]
