# Generated by Django 2.2.24 on 2021-08-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_auto_20210607_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='county',
            field=models.CharField(blank=True, max_length=50, verbose_name='county'),
        ),
    ]
