# Generated by Django 2.2.24 on 2021-11-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_auto_20211101_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedAppField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Help Text')),
                ('choices', models.CharField(blank=True, help_text='Comma separated options where applicable', max_length=1000, verbose_name='Choices')),
                ('default_value', models.CharField(blank=True, default='', max_length=200, verbose_name='Default Value')),
                ('app_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_fields', to='chapters.ChapterMembershipAppField')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
            ],
            options={
                'unique_together': {('app_field', 'chapter')},
            },
        ),
    ]
