# Generated by Django 2.2.24 on 2021-12-05 22:40

from django.db import migrations, models
import django.db.models.deletion
import tendenci.apps.chapters.models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_auto_20211205_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMembershipFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=260, upload_to=tendenci.apps.chapters.models.file_directory)),
                ('chapter_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chapters.ChapterMembership')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chapters.ChapterMembershipAppField')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='chaptermembershipfile',
            unique_together={('chapter_membership', 'field')},
        ),
    ]
