# Generated by Django 2.2.24 on 2021-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_customizedappfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermembership',
            name='renew_from_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
