# Generated by Django 3.2.5 on 2021-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_customizedtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='external_payment_link',
            field=models.URLField(blank=True, default='', help_text='A third party payment link. If specified, users will be redirected to it to pay their chapter memberships dues online.', verbose_name='External payment link'),
        ),
    ]
