# Generated by Django 2.2.24 on 2021-11-14 21:13

from django.db import migrations
import tendenci.libs.tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_chaptermembership_renew_from_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptermembershipapp',
            name='renewal_confirmation_text',
            field=tendenci.libs.tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chaptermembershipapp',
            name='renewal_description',
            field=tendenci.libs.tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
