# Generated by Django 2.2.24 on 2021-11-16 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tendenci.libs.tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0012_auto_20211114_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(editable=False, max_length=50)),
                ('notice_name', models.CharField(max_length=250, verbose_name='Name')),
                ('num_days', models.IntegerField(default=0)),
                ('notice_time', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('attimeof', 'At Time Of')], max_length=20, verbose_name='Notice Time')),
                ('notice_type', models.CharField(choices=[('apply', 'Apply Date'), ('renewal', 'Renewal Date'), ('expiration', 'Expiration Date'), ('approve', 'Approval Date'), ('reject', 'Reject Date'), ('approve_renewal', 'Renewal Approval Date'), ('reject_renewal', 'Renewal Reject Date')], max_length=20, verbose_name='For Notice Type')),
                ('subject', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('html', 'HTML')], default='html', max_length=10, verbose_name='Content Type')),
                ('sender', models.EmailField(blank=True, max_length=255, null=True)),
                ('sender_display', models.CharField(blank=True, max_length=255, null=True)),
                ('email_content', tendenci.libs.tinymce.models.HTMLField(verbose_name='Email Content')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('creator_username', models.CharField(max_length=150, null=True)),
                ('owner_username', models.CharField(max_length=150, null=True)),
                ('status_detail', models.CharField(choices=[('active', 'Active'), ('admin_hold', 'Admin Hold')], default='active', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('chapter', models.ForeignKey(blank=True, help_text="Note that if you don't select a chapter, the notice will go out to all chapter members.", null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.Chapter')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_membership_creator_notices', to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(blank=True, help_text="Note that if you don't select a membership type, the notice will go out to all members.", null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.ChapterMembershipType')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_membership_owner_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(editable=False, max_length=50)),
                ('notice_sent_dt', models.DateTimeField(auto_now_add=True)),
                ('num_sent', models.IntegerField()),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chapters.Notice')),
            ],
            options={
                'verbose_name': 'Notice Log',
                'verbose_name_plural': 'Notice Logs',
            },
        ),
        migrations.CreateModel(
            name='NoticeDefaultLogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(editable=False, max_length=50)),
                ('emails_sent', models.CharField(default='', max_length=500)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('chapter_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_log_records', to='chapters.ChapterMembership')),
                ('notice_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_log_records', to='chapters.NoticeLog')),
            ],
            options={
                'verbose_name': 'Notice Log Record',
                'verbose_name_plural': 'Notice Log Records',
            },
        ),
    ]
