# Generated by Django 2.2.24 on 2021-11-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0005_auto_20210916_1726'),
        ('chapters', '0013_notice_noticedefaultlogrecord_noticelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='newsletter_group',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ng_chapters', to='user_groups.Group'),
        ),
    ]
