# Generated by Django 2.2.24 on 2021-11-26 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tendenci.apps.base.fields
import tendenci.apps.chapters.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chapters', '0014_chapter_newsletter_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMembershipImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_line', models.CharField(default='', max_length=3000, verbose_name='Header Line')),
                ('override', models.IntegerField(choices=[(0, 'Blank Fields'), (1, 'All Fields (override)')], default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('num_processed', models.IntegerField(default=0)),
                ('summary', models.CharField(default='', max_length=500, null=True, verbose_name='Summary')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('preprocessing', 'Pre_processing'), ('preprocess_done', 'Pre_process Done'), ('processing', 'Processing'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('complete_dt', models.DateTimeField(null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('upload_file', models.FileField(max_length=260, null=True, upload_to=tendenci.apps.chapters.models.get_import_file_path, verbose_name='Upload File')),
                ('recap_file', models.FileField(max_length=260, null=True, upload_to='', verbose_name='Recap File')),
                ('key', models.CharField(default='', max_length=50, verbose_name='Key')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapters.Chapter')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterMembershipImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', tendenci.apps.base.fields.DictField(verbose_name='Row Data')),
                ('row_num', models.IntegerField(verbose_name='Row #')),
                ('action_taken', models.CharField(max_length=20, null=True, verbose_name='Action Taken')),
                ('error', models.CharField(default='', max_length=500, verbose_name='Error')),
                ('mimport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_data', to='chapters.ChapterMembershipImport')),
            ],
        ),
    ]
