# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-29 22:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_sponsor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='default_yes',
            field=models.BooleanField(default=False, help_text='Default the Add-on to yes so the registrant has to purposefully opt-out', verbose_name='Default to yes'),
        ),
    ]
