# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 14:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_addon_default_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='regconfpricing',
            name='registration_cap',
            field=models.IntegerField(default=0, help_text='The maximum number of registrants allowed for this pricing. 0 indicates unlimited. Note: this number should not exceed the specified registration limit.', verbose_name='Registration limit'),
        ),
        migrations.AddField(
            model_name='regconfpricing',
            name='spots_taken',
            field=models.IntegerField(default=0),
        ),
    ]
