# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_range',
            field=models.BooleanField(default=False, verbose_name='Age Range?'),
        ),
        migrations.AddField(
            model_name='event',
            name='high_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='event',
            name='low_age',
            field=models.IntegerField(blank=True, default=0, verbose_name='From'),
        ),
    ]
