# Generated by Django 3.2.18 on 2023-03-02 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_registrationconfiguration_external_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationconfiguration',
            name='cancel_by_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancel by'),
        ),
        migrations.AddField(
            model_name='registrationconfiguration',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21, verbose_name='Cancellation Fee'),
        ),
        migrations.AddField(
            model_name='registrationconfiguration',
            name='cancellation_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Cancellation Percent'),
        ),
    ]
