# Generated by Django 3.2.18 on 2023-03-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_registrationconfiguration_external_payment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEUCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ceucategory')),
            ],
            options={
                'verbose_name_plural': 'Continuing Education Unit Categories',
                'ordering': ('name',),
            },
        ),
    ]
