# Generated by Django 3.2.12 on 2022-11-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
        ('events', '0018_registrationconfiguration_external_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.course'),
        ),
    ]
