# Generated by Django 3.2.16 on 2023-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_registrationconfiguration_external_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
