# Generated by Django 3.2.18 on 2023-04-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_ceucategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceucategory',
            options={'ordering': ('name',), 'verbose_name': 'Continuing Education Unit Category', 'verbose_name_plural': 'Continuing Education Unit Categories'},
        ),
        migrations.CreateModel(
            name='EventCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_count', models.PositiveSmallIntegerField(default=0)),
                ('alternate_ceu_id', models.CharField(blank=True, max_length=150, null=True)),
                ('available', models.BooleanField(default=True)),
                ('ceu_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.ceucategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
