# Generated by Django 3.2.12 on 2022-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_registrant_certification_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='begin_dt',
            field=models.DateField(null=True, blank=True, verbose_name='Beginning on'),
        ),
        migrations.AddField(
            model_name='registration',
            name='key_contact_fax',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Training Contact Fax'),
        ),
        migrations.AddField(
            model_name='registration',
            name='key_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Training Contact'),
        ),
        migrations.AddField(
            model_name='registration',
            name='key_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Training Contact Phone'),
        ),
        migrations.AddField(
            model_name='registration',
            name='need_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='nights',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
