# Generated by Django 3.2.18 on 2023-05-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20230425_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_relationship',
            field=models.CharField(choices=[('parent', 'Is Parent Event'), ('child', 'Is Child Event')], default='parent', help_text="Select 'child' if this is a sub-event of a larger symposium", max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(help_text='Larger symposium this event is a part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
