# Generated by Django 3.2.18 on 2023-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20230425_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcredit',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='eventcredit',
            name='event',
        ),
        migrations.AddField(
            model_name='eventcredit',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
