# Generated by Django 3.2.18 on 2023-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20230511_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceucategory',
            name='code',
            field=models.CharField(default='ABC', max_length=15),
            preserve_default=False,
        ),
    ]
