# Generated by Django 3.2.16 on 2023-05-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_speaker_position'),
        ('events', '0021_auto_20221116_1400'),
    ]

    operations = [
    ]
