# Generated by Django 3.2.18 on 2023-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_merge_0019_speaker_position_0021_auto_20221116_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonoption',
            name='title',
            field=models.CharField(blank=True, help_text='If only one option, please use the first "Title" field at the top of the form instead. Radio buttons will not be displayed if more than one option is not offered.', max_length=100, null=True),
        ),
    ]
