# Generated by Django 3.2.19 on 2023-05-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20230302_1727'),
        ('events', '0022_merge_0019_speaker_position_0021_auto_20221116_1400'),
    ]

    operations = [
    ]
