# Generated by Django 3.2.19 on 2023-07-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_merge_20230524_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEUCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=15)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ceucategory')),
            ],
            options={
                'verbose_name': 'Continuing Education Unit Category',
                'verbose_name_plural': 'Continuing Education Unit Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EventCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_count', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('alternate_ceu_id', models.CharField(blank=True, max_length=150, null=True)),
                ('available', models.BooleanField(default=False)),
                ('ceu_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ceucategory')),
                ('event', models.ManyToManyField(blank=True, to='events.Event')),
            ],
        ),
    ]
