# Generated by Django 3.2.18 on 2023-07-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_ceucategory_eventcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcredit',
            name='ceu_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ceucategory'),
        ),
        migrations.AlterField(
            model_name='eventcredit',
            name='credit_count',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
