# Generated by Django 3.2.18 on 2023-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20230705_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, help_text='Optional code representing this event.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_name',
            field=models.CharField(blank=True, help_text='Shorter name to display when space is limited (optional).', max_length=150, null=True),
        ),
    ]
