# Generated by Django 3.2.18 on 2023-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20230712_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='regconfpricing',
            name='days_price_covers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of days this price covers (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='addonoption',
            name='title',
            field=models.CharField(blank=True, help_text='If only one option, please use the first "Title" field at the top of the form instead. Radio buttons will not be displayed if more than one option is not offered.', max_length=100, null=True),
        ),
    ]
