# Generated by Django 3.2.19 on 2023-08-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20230712_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='regconfpricing',
            name='days_price_covers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of days this price covers (optional).', null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='attendance_dates',
            field=models.JSONField(blank=True, help_text='The dates this registrant will be attending.', null=True),
        ),
        migrations.AlterField(
            model_name='addonoption',
            name='title',
            field=models.CharField(blank=True, help_text='If only one option, please use the first "Title" field at the top of the form instead. Radio buttons will not be displayed if more than one option is not offered.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RegistrantChildEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Is Checked In?')),
                ('checked_in_dt', models.DateTimeField(null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('child_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrant')),
            ],
        ),
    ]
