# Generated by Django 3.2.18 on 2023-07-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20230712_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='attendance_dates',
            field=models.JSONField(blank=True, help_text='The dates this registrant will be attending.', null=True),
        ),
    ]
