# Generated by Django 3.2.18 on 2023-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20230809_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='Is Checked Out?'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='checked_out_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
