# Generated by Django 3.2.18 on 2023-07-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_registrant_attendance_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantChildEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=False, verbose_name='Is Checked In?')),
                ('checked_in_dt', models.DateTimeField(null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('child_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrant')),
            ],
        ),
    ]
