# Generated by Django 3.2.18 on 2023-08-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20230810_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrantCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=1, default=0, help_text='Defaults to value set in EventCredit, but can be overridden.', max_digits=5)),
                ('released', models.BooleanField(default=False, help_text='Indicates credits can be displayed on a certificate.')),
                ('event_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcredit')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.registrant')),
            ],
        ),
    ]
