# Generated by Django 3.2.18 on 2023-08-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_registrantcredits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrantcredits',
            options={'verbose_name_plural': 'Registrant Credits'},
        ),
    ]
