# Generated by Django 3.2.16 on 2023-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20230817_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationconfiguration',
            name='reply_to_receive_notices',
            field=models.BooleanField(default=False, help_text='Make the above reply-to address also receives the event-specific admin notices.', verbose_name='Reply-to receives notices'),
        ),
    ]
