# Generated by Django 3.2.18 on 2023-08-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20230817_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='use_zoom_integration',
            field=models.BooleanField(default=False, help_text='Use Zoom integration to allow launching Zoom meeting from Event.'),
        ),
        migrations.AddField(
            model_name='place',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, help_text='Zoom meeting ID for this Event. If none is set, will use Personal Zoom Meeting ID in Events Settings.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='zoom_meeting_passcode',
            field=models.CharField(blank=True, help_text='Zoom meeting passcode for this Event. If none is set, will use Personal Zoom Meeting Passcode in Events Settings.', max_length=50, null=True),
        ),
    ]
