# Generated by Django 3.2.18 on 2023-09-01 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20230830_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualEventCreditsLogicConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_period', models.PositiveSmallIntegerField(default=50, help_text='Number of minutes to earn 1 full credit.', verbose_name='Period (Number of Minutes per Credits Earned)')),
                ('full_credit_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Per period. Leave blank if using number of questions.', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Percent of Questions Correct for Full Credit')),
                ('full_credit_questions', models.PositiveSmallIntegerField(blank=True, help_text='Per period. Leave blank if using percentage.', null=True, verbose_name='Number of Questions for Full Credit')),
                ('half_credits_allowed', models.BooleanField(default=True, verbose_name='Half Credits Allowed')),
                ('half_credit_periods', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if allowed for entirety of event', null=True, verbose_name='Number of Periods after which Half Credits Can be Earned')),
            ],
        ),
    ]
