# Generated by Django 3.2.18 on 2023-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_registrantcredits_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaff',
            name='include_on_certificate',
            field=models.BooleanField(default=False, help_text='Check to display name and role on certificate', verbose_name='Include on Certificate'),
        ),
    ]
