# Generated by Django 3.2.18 on 2023-09-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_virtualeventcreditslogicconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualeventcreditslogicconfiguration',
            options={'verbose_name': 'Virtual Event Credits Logic Configuration', 'verbose_name_plural': 'Virtual Event Credits Logic Configuration'},
        ),
    ]
