# Generated by Django 3.2.23 on 2023-12-15 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_applied_cancellation_fees'),
        ('payments', '0005_refund_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0031_auto_20231017_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='regconfpricing',
            name='assets_purchase',
            field=models.BooleanField(default=False, verbose_name='Pricing available for assets purchase'),
        ),
        migrations.CreateModel(
            name='AssetsPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=21, verbose_name='Amount')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('status_detail', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentmethod')),
                ('pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.regconfpricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
