# Generated by Django 3.2.18 on 2023-09-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20230918_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAPIConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Used to easily identify this Zoom account.', max_length=255)),
                ('sdk_client_id', models.CharField(help_text='Client ID for Zoom SDK app (to launch Zoom from Event).', max_length=100)),
                ('sdk_client_secret', models.CharField(help_text='Client secret for Zoom SDK app (to launch Zoom from Event).', max_length=255)),
                ('oauth_account_id', models.CharField(help_text='Account ID for Zoom Server to Server OAuth app (get meeting/webinar info).', max_length=100)),
                ('oauth_client_id', models.CharField(help_text='Client ID for Zoom Server to Server OAuth app (get meeting/webinar info).', max_length=100)),
                ('oauth_client_secret', models.CharField(help_text='Client secret for Zoom Server to Server Oauth app (get meeting/webinar info).', max_length=255)),
            ],
            options={
                'verbose_name': 'Zoom API Configuration',
                'verbose_name_plural': 'Zoom API Configurations',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='zoom_api_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.zoomapiconfiguration'),
        ),
    ]
