# Generated by Django 3.2.23 on 2024-01-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20231215_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='certificate_template',
            field=models.CharField(blank=True, choices=[('', ''), ('events/registrants/certificate-symposium.html', 'certificate-symposium.html'), ('events/registrants/certificate-single-event.html', 'certificate-single-event.html')], default='', max_length=100),
        ),
    ]
