# Generated by Django 3.2.18 on 2023-09-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20230920_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomapiconfiguration',
            name='use_as_default',
            field=models.BooleanField(default=False, help_text='Check to use this as the default option when selecting a Zoom API Configuration (only one default).'),
        ),
    ]
