# Generated by Django 3.2.18 on 2023-09-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_virtualeventcreditslogicconfiguration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualeventcreditslogicconfiguration',
            name='credit_period_questions',
            field=models.PositiveSmallIntegerField(default=4, help_text='Total number of questions per credit period.', verbose_name='Number of Questions for each credit period'),
        ),
        migrations.AddField(
            model_name='virtualeventcreditslogicconfiguration',
            name='half_credit_credits',
            field=models.PositiveIntegerField(default=0, help_text='Leave 0 if there is no requirement.', verbose_name='Number of full credits required before half credits can be earned.'),
        ),
        migrations.AlterField(
            model_name='virtualeventcreditslogicconfiguration',
            name='half_credit_periods',
            field=models.PositiveSmallIntegerField(default=0, help_text='Leave 0 if allowed for entirety of event', verbose_name='Number of Periods after which Half Credits Can be Earned'),
        ),
    ]
