# Generated by Django 3.2.23 on 2024-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_type_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
