# Generated by Django 3.2.18 on 2023-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20230908_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_zoom_webinar',
            field=models.BooleanField(default=False, help_text='Check if the Zoom meeting is a webinar.'),
        ),
    ]
