# Generated by Django 3.2.18 on 2023-09-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_zoomapiconfiguration_use_as_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='zoom_api_configuration',
            field=models.ForeignKey(blank=True, help_text="Zoom API credentials for the account you want to use for this Event's meeting.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.zoomapiconfiguration'),
        ),
        migrations.AlterField(
            model_name='place',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, help_text='Zoom meeting ID for this Event.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='zoom_meeting_passcode',
            field=models.CharField(blank=True, help_text='Zoom meeting passcode for this Event.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoomapiconfiguration',
            name='use_as_default',
            field=models.BooleanField(default=False, help_text='Check to use this as the default option when selecting a Zoom API Configuration. Only one configuration can be used as default.'),
        ),
    ]
