# Generated by Django 4.2.21 on 2025-07-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagging.fields
import tendenci.apps.events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0036_add_groups_through_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to=tendenci.apps.events.models.eventfile_directory)),
                ('guid', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(blank=True, choices=[('Document', 'Document'), ('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio'), ('Slide Show', 'Slide Show')], default='Document', max_length=20)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('creator_username', models.CharField(max_length=150)),
                ('owner_username', models.CharField(max_length=150)),
                ('status_detail', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('creator', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.event')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
