# Generated by Django 4.2.27 on 2026-04-13 11:39

from django.db import migrations, models
import tendenci.apps.events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_eventfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfile',
            name='file_url',
            field=models.URLField(blank=True, default='', verbose_name='File URL'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tendenci.apps.events.models.eventfile_directory),
        ),
    ]
