# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 11:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20180315_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('', 'SELECT ONE'), ('Committee', 'Committee'), ('Reporting', 'Reporting'), ('Study Group', 'Study Group'), ('Technical Interest Group', 'Technical Interest Group'), ('Other', 'Other')], default='Reporting', max_length=200, verbose_name='Type'),
        ),
    ]
