# Generated by Django 3.2.12 on 2022-06-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200902_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photocategory')),
            ],
            options={
                'verbose_name_plural': 'Photo Categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='photoset',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_photo_sets', to='photos.photocategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='photoset',
            name='sub_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cat_photo_sets', to='photos.photocategory', verbose_name='Sub Category'),
        ),
    ]
