# Generated by Django 3.2.12 on 2022-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20220622_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
