# Generated by Django 2.2.16 on 2020-11-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeemail',
            name='emails',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
