from django.utils.translation import ugettext as _

def html_footer():
    """Return the contents of the HTML email footer.

    This footer provides important exposure for the Tendenci project, for which
    most of the development costs are funded by hosted Tendenci subscriptions.

    This footer is implemented in code, rather than templates, so that it can't
    be trivially removed by hosted customers. If you need to remove this footer,
    please maintain a fork the tendenci repository. For discussion on this, see:

    https://github.com/tendenci/tendenci/pull/654/

    """
    return (
        '<p align="center">' +
        _('This e-mail was generated by Tendenci&reg; - The Open Source AMS') +
        ' <a href="https://www.tendenci.com">www.tendenci.com</a>' +
        '</p>')


def text_footer():
    """Return the contents of the text-only email footer."""
    return (
        _('This e-mail was generated by Tendenci - The Open Source AMS') +
        ' https://www.tendenci.com')
