# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 17:45


from django.db import migrations, models
import django.db.models.deletion
import tendenci.apps.user_groups.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180315_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_groups.Group'),
        ),
    ]
