# Generated by Django 5.2.13 on 2026-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='salary_increase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='sec',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SEC'),
        ),
        migrations.AlterField(
            model_name='career',
            name='company',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Company'),
        ),
    ]
