# Generated by Django 5.2.13 on 2026-07-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthentikUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('a_user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnPushedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
