# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 18:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0003_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='account_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='country',
            field=models.CharField(default='US', max_length=5),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='default_currency',
            field=models.CharField(default='usd', max_length=5),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='status_detail',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
