# Generated by Django 2.2.16 on 2020-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0004_auto_20180724_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='creator_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='stripeaccount',
            name='owner_username',
            field=models.CharField(max_length=150),
        ),
    ]
