# Generated by Django 3.2.16 on 2023-03-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_show_for_donation'),
        ('stripe', '0005_auto_20200902_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeaccount',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity', unique=True),
        ),
    ]
