# Generated by Django 3.2.16 on 2023-08-29 13:44

from django.db import migrations


def migrate_scope(apps, schema_editor):
    StripeAccount = apps.get_model("stripe", "StripeAccount")
    StripeAccount.objects.filter(scope='read_write').update(scope='standard')

class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0006_alter_stripeaccount_entity'),
    ]

    operations = [
        migrations.RunPython(migrate_scope),
    ]
