# Generated by Django 3.2.18 on 2023-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20230630_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='applied_cancellation_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
