# Generated by Django 4.2.21 on 2025-09-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoice_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to_address2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
