# Generated by Django 4.2.21 on 2025-09-27 16:43

from django.db import migrations


def populate_address2_to_invoice_(apps, schema_editor):
    # populate address2 for invoices from corp memberships
    CorpMembership = apps.get_model('corporate_memberships', 'CorpMembership')
    for corp_membership in CorpMembership.objects.filter(status=True, status_detail__in=['pending', 'active']):
        corp_profile = corp_membership.corp_profile
        invoice = corp_membership.invoice
        if invoice and corp_profile.address2:
            invoice.bill_to_address2 = corp_profile.address2
            invoice.ship_to_address2 = corp_profile.address2
            invoice.save(update_fields=['bill_to_address2', 'ship_to_address2'])


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_bill_to_address2_invoice_ship_to_address2'),
    ]

    operations = [
        migrations.RunPython(populate_address2_to_invoice_),
    ]
