# Generated by Django 2.2.10 on 2020-04-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendenci_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('position',)},
        ),
    ]
