# Generated by Django 2.2.14 on 2020-07-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('directories', '0009_auto_20190816_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.Region'),
        ),
    ]
