# Generated by Django 2.2.14 on 2020-07-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0011_auto_20200731_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Entity'),
        ),
    ]
