# Generated by Django 2.2.16 on 2020-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0012_auto_20200731_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='creator_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='directory',
            name='owner_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='directorypricing',
            name='creator_username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='directorypricing',
            name='owner_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
