# Generated by Django 2.2.16 on 2020-10-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0013_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='cats',
            field=models.ManyToManyField(related_name='directory_cats', to='directories.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='directory',
            name='sub_cats',
            field=models.ManyToManyField(related_name='directory_subcats', to='directories.Category', verbose_name='Sub Categories'),
        ),
    ]
