# Generated by Django 2.2.16 on 2020-10-28 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directories', '0018_affiliaterequest_allowedconnection_requestemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliateship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliateship_affiliate_directories', to='directories.Directory')),
                ('creator', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliateship_directories', to='directories.Directory')),
            ],
            options={
                'verbose_name': 'Directory Affiliateship',
                'unique_together': {('directory', 'affiliate')},
            },
        ),
        migrations.AddField(
            model_name='directory',
            name='affiliates',
            field=models.ManyToManyField(through='directories.Affiliateship', to='directories.Directory'),
        ),
    ]
