# Generated by Django 2.2.16 on 2020-11-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0019_auto_20201028_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliateship',
            options={'ordering': ['directory', 'affiliate'], 'verbose_name': 'Directory Affiliateship'},
        ),
    ]
