# Generated by Django 2.2.18 on 2021-02-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0020_auto_20201101_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affliated_cats', models.ManyToManyField(related_name='allowed_connections', to='directories.Category', verbose_name='Affliated Categories')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='directories.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Allowed Connection',
                'verbose_name_plural': 'Allowed Connections',
                'ordering': ('cat',),
            },
        ),
        migrations.DeleteModel(
            name='AllowedConnection',
        ),
    ]
