# Generated by Django 4.2.14 on 2024-09-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directories', '0024_auto_20210808_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorypricing',
            name='include_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directorypricing',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Example: 0.0825 for 8.25%.', max_digits=5),
        ),
    ]
