# Generated by Django 5.2.13 on 2026-05-17 16:07

from django.db import migrations
import logging
logger = logging.getLogger(__name__)

def remove_old_static_refs_from_templates(apps, schema_editor):
    """
    Remove references to the old tendenci.apps.theme.templatetags.static
    tags file from customised templates (via a {% load static %} tag,
    as this file has been renamed and the tendenci static tags are now
    loaded via the TEMPLATES setting in settings.py
    """
    import os
    import glob
    from tendenci.apps.theme.utils import get_theme_root

    STATIC_LOADER = '{% load static %}'
    dir_path = get_theme_root()
    file_glob = f'{dir_path}/templates/**/*.html'
    logger.info('') # Newline or the first log gets appended to the "applying .." message
    for file in glob.glob(file_glob, recursive=True):
        with open(file) as f:
            content = f.read()
            if STATIC_LOADER in content:
                content = content.replace(STATIC_LOADER, '')
                with open(file, 'w') as f:
                    f.write(content)
                    logger.info(f'\tDeleted "{STATIC_LOADER}" tag from {file}')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(remove_old_static_refs_from_templates, migrations.RunPython.noop),
    ]
