# Generated by Django 5.2.14 on 2026-07-25 15:13

from django.db import migrations
import logging
logger = logging.getLogger(__name__)

SINGLE_QUOTE = "'"
DOUBLE_QUOTE = '"'

class Replace:
    find_str: str
    with_str: str
    find_str_flipped_quotes: str

    def flip_quotes(self, str_to_flip:str)->str:
        if (DOUBLE_QUOTE in str_to_flip):
            return str_to_flip.replace(DOUBLE_QUOTE, SINGLE_QUOTE)
        if (SINGLE_QUOTE in str_to_flip):
            return str_to_flip.replace(SINGLE_QUOTE, DOUBLE_QUOTE)
        return None

    def __init__(self,find_str, with_str):
        self.find_str = find_str
        self.with_str = with_str
        self.find_str_flipped_quotes = self.flip_quotes(self.find_str)


REPLACEMENTS = [
    Replace(".datepicker({ dateFormat: 'yy-mm-dd' })", ".datepicker({ dateFormat: '{{ DATEPICKER_DATE_FORMAT }}' })"),
    Replace(".timepicker({'timeFormat': 'h:i A'})", ".timepicker({'timeFormat': '{{ DATEPICKER_TIME_FORMAT }}' })"),
    Replace('dateFormat: "yy-mm-dd",', 'dateFormat: "{{DATEPICKER_DATE_FORMAT}}",'),
    Replace('<h2>{{ event.start_dt|date:"l, M j, Y" }} - {{ event.end_dt|date:"l, M j, Y" }}',
            '<h2>{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATE_FORMAT" }}  - {{ event.end_dt|date:"l" }}, {{ event.end_dt|date:"DATE_FORMAT" }}'),
    Replace('{{ event.start_dt|date:"l, M j, Y P" }} - {{ event.end_dt|date:"l, M j, Y P" }}',
            '{{ event.start_dt|date:"DATETIME_FORMAT" }}  - {{ event.end_dt|date:"l" }}, {{ event.end_dt|date:"DATETIME_FORMAT" }}'),
    Replace('{{ span.start_dt|date:"l, j-M-Y" }} {{ event.start_dt|date:"P" }} - {{ span.end_dt|date:"l, j-M-Y" }} {{ event.end_dt|date:"P" }}',
            '{{ span.start_dt|date:"l" }}, {{ span.start_dt|date:"SHORT_DATE_FORMAT" }} {{ event.start_dt|date:"P" }} - {{ span.end_dt|date:"l" }}, {{ span.end_dt|date:"SHORT_DATE_FORMAT" }} {{ event.end_dt|date:"P" }}'),
    Replace('{{ event.start_dt|date:"l, M j, Y P" }}', '{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATETIME_FORMAT" }}'),
    Replace('{% if event.start_dt|date:"D, M. j, Y" != event.end_dt|date:"D, M. j, Y" %}'
          , '{% if event.start_dt|date:"SHORT_DATE_FORMAT" != event.end_dt|date:"SHORT_DATE_FORMAT" %}'),
    Replace('{{ event.start_dt|date:"l, M j, Y" }} - {{ event.end_dt|date:"l, M j, Y" }}',
            '{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATE_FORMAT" }} - {{ event.end_dt|date:"l" }}, {{ event.end_dt|date:"DATE_FORMAT" }}'),
    Replace('{{ event.start_dt|date:"l, M j, Y P" }} - {{ event.end_dt|date:"l, M j, Y P" }}',
            '{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATETIME_FORMAT" }} - {{ event.end_dt|date:"l" }}, {{ event.end_dt|date:"DATETIME_FORMAT" }}'),
    Replace('{{ event.start_dt|date:"l, M j, Y P" }}</time>', '{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATE_FORMAT" }}</time>'),
    Replace('{{ event.start_dt|date:"D, M j, Y" }}', '{{ event.start_dt|date:"D" }}, {{ event.start_dt|date:"DATE_FORMAT" }}'),
    Replace('{{ event.start_dt|date:"l, M j, Y" }}</time> ', '{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATE_FORMAT" }}</time>'),
    Replace('{{ event.end_dt|date:"l, M j, Y" }}</time>', '{{ event.end_dt|date:"l" }}, {{ event.end_dt|date:"DATE_FORMAT" }}</time>'),
    Replace("{{ event.start_dt }}", "{{ event.start_dt|date:'DATE_FORMAT' }}"),
    Replace("{{ event.date }}", "{{ event.date|date:'DATE_FORMAT' }}"),
    Replace('{{ span.start_dt|date:"D, N j, Y" }}', '{{ span.start_dt|date:"D" }}, {{ span.start_dt|date:"DATE_FORMAT" }}'),
    Replace('{{ event.start_dt|date:"l, M j, Y P" }}</time>', '{{ event.start_dt|date:"l" }}, {{ event.start_dt|date:"DATETIME_FORMAT" }}</time>'),
    Replace('{{ reg.registration.event.start_dt }} - {{ reg.registration.event.end_dt }}', '{{ reg.registration.event.start_dt|date:"DATE_FORMAT" }} - {{ reg.registration.event.end_dt|date:"DATE_FORMAT" }}'),
    Replace("|date:'M j Y g:i A'", "|date:'SHORT_DATETIME_FORMAT'"),
    Replace("|date:'m/d/Y'", "|date:'SHORT_DATE_FORMAT'"),
    Replace("|date:'m/d/y P'", "|date:'SHORT_DATE_FORMAT'"),
    Replace("|date:'n/j/Y'", "|date:'SHORT_DATE_FORMAT'"),
    Replace('|date:"short"', '|date:"SHORT_DATE_FORMAT"'),
    Replace('|date:"F j, Y"}}', '|date:"DATE_FORMAT"}}'),
    Replace('|date:"F jS, Y"', '|date:"DATE_FORMAT" '),
    Replace("|date:'N d, Y'", "|date:'DATE_FORMAT'"),
    Replace('|date:"N n, Y"', "|date:'DATE_FORMAT'"),
    Replace("|date:'N j, Y'", "|date:'DATE_FORMAT'"),
    Replace("|date:'M d, Y'", "|date:'DATE_FORMAT'"),
    Replace('|date:"M j, Y"', '|date:"DATE_FORMAT"'),
    Replace("|date:'M. j'", "|date:'DATE_FORMAT'"),
    Replace("|date:'M. j, Y'", "|date:'DATE_FORMAT'"),
    Replace('|date:"D, M. j"', '|date:"DATE_FORMAT"'),
    Replace('|date:"D, M. j, Y"', '|date:"DATE_FORMAT"'),
]


def replace_hard_coded_date_formatting_in_templates(apps, schema_editor):
    """
    Replace hard coded date formatting strings with appropriate
    variables from settings.py
    """
    import os
    import glob
    from tendenci.apps.theme.utils import get_theme_root

    dir_path = get_theme_root()
    file_glob = f'{dir_path}/templates/**/*.html'
    logger.info('') # Newline or the first log gets appended to the "applying .." message
    for file in glob.glob(file_glob, recursive=True):
        with open(file) as f:
            content = f.read()
            logger.debug(f'  Checking template {file} for hard-coded date formatting')
            dirty = False
            for replace in REPLACEMENTS:
                if replace.find_str in content:
                    dirty = True
                    content = content.replace(replace.find_str, replace.with_str)
                if replace.find_str_flipped_quotes and replace.find_str_flipped_quotes in content:
                    dirty = True
                    content = content.replace(replace.find_str_flipped_quotes, replace.with_str)
            if dirty:
                with open(file, 'w') as f:
                    f.write(content)
                    logger.info(f'\tReplaced one or more hard-coded dateformats in {file}')

class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_hard_coded_date_formatting_in_templates, migrations.RunPython.noop),
    ]
