# Generated by Django 3.2.12 on 2022-11-03 16:17

from django.db import migrations, models
import tendenci.libs.tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tendenci.libs.tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_score',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='schoolcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Category Name'),
        ),
    ]
