# Generated by Django 3.2.12 on 2022-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20221103_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='min_score',
            field=models.DecimalField(decimal_places=0, default=80, max_digits=3),
        ),
    ]
