# Generated by Django 3.2.12 on 2022-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20221113_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='exam',
        ),
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
