# Generated by Django 3.2.12 on 2022-12-28 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0004_outsideschool_certification_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='apply_to',
            field=models.IntegerField(blank=True, verbose_name='Apply to diamond', choices=[(0, 0),(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, help_text='Apply to a diamond number if applicable'),
        ),
        migrations.CreateModel(
            name='UserCertData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_dt', models.DateField(null=True, verbose_name='Certification Date')),
                ('diamond_1_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 1')),
                ('diamond_2_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 2')),
                ('diamond_3_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 3')),
                ('diamond_4_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 4')),
                ('diamond_5_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 5')),
                ('diamond_6_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 6')),
                ('diamond_7_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 7')),
                ('diamond_8_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 8')),
                ('diamond_9_dt', models.DateField(blank=True, null=True, verbose_name='Diamond Date 9')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Certification Data',
                'verbose_name_plural': 'User Certification Data',
                'unique_together': {('user', 'certification')},
            },
        ),
    ]
