# Generated by Django 3.2.12 on 2022-11-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20221127_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='certification_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.certification'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='registrant_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
