# Generated by Django 3.2.12 on 2023-01-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20221228_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='location_type',
            field=models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite'), ('outside', 'Outside')], default='online', max_length=10, verbose_name='Type'),
        ),
    ]
