# Generated by Django 3.2.12 on 2022-11-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20221127_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='diamond_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='certification',
            name='diamond_period',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='certification',
            name='diamond_required_activity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Required Teaching Activity'),
        ),
        migrations.AddField(
            model_name='certification',
            name='diamond_required_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Required Credits'),
        ),
        migrations.AddField(
            model_name='certification',
            name='diamond_required_online_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Required Online Credits'),
        ),
        migrations.AddField(
            model_name='certification',
            name='enable_diamond',
            field=models.BooleanField(default=False, help_text='Enable diamond to be added'),
        ),
    ]
