# Generated by Django 3.2.16 on 2023-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_corptranscriptszipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Course Name'),
        ),
    ]
