# Generated by Django 3.2.16 on 2023-02-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainings.exam'),
        ),
    ]
