# Generated by Django 3.2.16 on 2023-02-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0009_transcript_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluevoltExamImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('num_inserted', models.PositiveIntegerField(blank=True, null=True)),
                ('status_detail', models.CharField(default='Pending', max_length=10, verbose_name='Status')),
                ('result_detail', models.TextField(blank=True, default='')),
                ('run_start_date', models.DateTimeField(blank=True, null=True,)),
                ('run_finish_date', models.DateTimeField(blank=True, null=True,)),
                ('run_by', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bluevolt Exam Import',
                'verbose_name_plural': 'Bluevolt Exam Imports',
            },
        ),
    ]
