# Generated by Django 3.2.16 on 2023-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_bluevoltexamimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingactivity',
            name='activity_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
