# Generated by Django 3.2.16 on 2023-03-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_alter_outsideschool_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
