# Generated by Django 3.2.16 on 2023-03-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
