# Generated by Django 3.2.23 on 2024-02-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0014_transcript_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredit',
            fields=[
            ],
            options={
                'verbose_name': 'User Credits',
                'verbose_name_plural': 'User Credits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trainings.usercertdata',),
        ),
    ]
