# Generated by Django 3.2.23 on 2024-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0015_usercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='required_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='usercertdata',
            name='applicable_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
