# Generated by Django 3.2.23 on 2024-03-25 13:57

from django.db import migrations
from django.core.management import call_command


def populate_applicable_credits(apps, schema_editor):
    call_command('update_applicable_credits')


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20240325_1244'),
    ]

    operations = [
        migrations.RunPython(populate_applicable_credits)
    ]
