# Generated by Django 3.2.23 on 2025-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0017_auto_20240325_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsideschool',
            name='training_hours',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
