# Generated by Django 4.2.21 on 2025-09-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0018_outsideschool_training_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
