# Generated by Django 3.2.12 on 2022-09-19 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0009_auto_20200902_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'be notified only when a new topic is added'), (2, 'be auto-subscribed to topics')], help_text="The auto-subscription works like you manually subscribed to watch each topic :\nyou will be notified when a topic will receive an answer. \nIf you choose to be notified only when a new topic is added. It meansyou will be notified only once when the topic is created : you won't be notified for the answers.", verbose_name='Subscription type')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions+', to='forums.forum', verbose_name='Forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_subscriptions+', to=settings.AUTH_USER_MODEL, verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Subscription to forum',
                'verbose_name_plural': 'Subscriptions to forums',
                'unique_together': {('user', 'forum')},
            },
        ),
    ]
