# Generated by Django 4.2.21 on 2025-09-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0010_forumsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsubscription',
            name='digest_type',
            field=models.CharField(choices=[('', 'No digest'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='', max_length=6),
        ),
    ]
