# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-19 12:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180315_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_function',
            field=models.CharField(blank=True, choices=[('GroupSubscription', 'Subscribe to Group'), ('GroupSubscriptionAuto', 'Subscribe to Group (Auto)'), ('EmailFirstName', 'First Name'), ('EmailLastName', 'Last Name'), ('EmailFullName', 'Full Name'), ('EmailPhoneNumber', 'Phone Number'), ('Recipients', 'Email to Recipients'), ('company', 'Company'), ('address', 'Address'), ('city', 'City'), ('state', 'State'), ('zipcode', 'Zip'), ('position_title', 'Position Title'), ('referral_source', 'Referral Source')], max_length=64, null=True, verbose_name='Special Functionality'),
        ),
    ]
