# Generated by Django 2.2.24 on 2021-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='summary_position',
            field=models.CharField(blank=True, help_text='Position in the onle line form entry summary. Row, Position or just Position.', max_length=6, verbose_name='Summary Position'),
        ),
        migrations.AlterField(
            model_name='form',
            name='completion_url',
            field=models.CharField(blank=True, help_text='Optionally, redirect to this page after form completion. Absolute URLS should begin with http. Relative URLs should begin with a forward slash (/).', max_length=1000, null=True, verbose_name='Completion URL'),
        ),
    ]
