# Generated by Django 3.2.13 on 2022-07-10 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0009_field_summary_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_memories', to='forms.field')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_memories', to='sessions.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_memories', to=settings.AUTH_USER_MODEL)),
                ('save_dt', models.DateTimeField())
            ],
        ),
    ]
