# Generated by Django 3.2.16 on 2023-10-24 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_field_summary_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='qty_enabled',
            field=models.BooleanField(default=False, help_text='If checked, a Quantity field will show on the form for users to set the quantity they wanted.', verbose_name='Allow users to specify quantity for the pricing option they chose'),
        ),
        migrations.AddField(
            model_name='formentry',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
