# Generated by Django 4.2.20 on 2025-04-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20231024_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ('-id',), 'permissions': (('publish_form', 'Can publish form'),), 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
