# Generated by Django 2.2.24 on 2021-09-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0004_auto_20200902_1545'),
        ('videos', '0011_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_groups.Group'),
        ),
    ]
