# Generated by Django 2.2.16 on 2020-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_auto_20190724_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creator_username',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner_username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
