# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 17:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='show_for_memberships',
            field=models.BooleanField(default=True, help_text='If checked and allows self add, this group will show as an option for the group field on membership applications'),
        ),
    ]
