# Generated by Django 2.2.16 on 2020-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0003_group_show_for_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='creator_username',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='owner_username',
            field=models.CharField(editable=False, max_length=150),
        ),
    ]
