# Generated by Django 3.2.16 on 2023-08-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0005_auto_20210916_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(help_text='Group Logo. .jpeg, .png and .gif only', blank=True, null=True, upload_to='groups', verbose_name='Logo'),
        ),
    ]
