# Generated by Django 3.2.12 on 2023-01-06 14:48

from django.db import migrations, models
import django.db.models.deletion
import tendenci.apps.user_groups.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0006_group_logo'),
        ('projects', '0005_auto_20221226_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(default=tendenci.apps.user_groups.utils.get_default_group, null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='user_groups.group'),
        ),
    ]
