# Generated by Django 3.2.23 on 2024-05-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_dt',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='Website URL'),
        ),
    ]
