# Generated by Django 3.2.23 on 2024-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20240501_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
    ]
