# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 17:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20180315_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
