# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 16:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181019_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_billing_address',
            field=models.BooleanField(default=True, verbose_name='Is billing address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_billing_address_2',
            field=models.BooleanField(default=False, verbose_name='Is billing address'),
        ),
    ]
