# Generated by Django 2.2.20 on 2021-04-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industries', '0002_auto_20200902_1545'),
        ('profiles', '0013_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industries.Industry'),
        ),
    ]
