# Generated by Django 2.2.20 on 2021-04-22 16:02

from django.db import migrations, models
import tendenci.apps.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20210408_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=tendenci.apps.profiles.models.profile_directory),
        ),
    ]
