# Generated by Django 3.2.5 on 2021-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20210801_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allow_anonymous_view',
            field=models.BooleanField(default=False, verbose_name='Public can view'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_member_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_member_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_user_edit',
            field=models.BooleanField(default=False, verbose_name='Signed in user can change'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_user_view',
            field=models.BooleanField(default=False, verbose_name='Signed in user can view'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
