# Generated by Django 3.2.12 on 2022-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20210801_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimport',
            name='exclude_is_active',
            field=models.BooleanField(default=False, verbose_name='Apply the above the Interactive/Non-interactive to new users ONLY.'),
        ),
    ]
