# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        pass


    def backwards(self, orm):
        pass


    models = {
        'legacy.legacyuser': {
            'Meta': {'object_name': 'LegacyUser', 'db_table': "u'users'", 'managed': 'False'},
            'address': ('django.db.models.fields.CharField', [], {'max_length': '150', 'blank': 'True'}),
            'address2': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'addresstype': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'adminnotes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'agreedtotos': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'articlespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'author': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ballotspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'calendareventspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'catalogspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'company': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'contentmanagerspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'coursespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'createdatetime': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'creatoruserid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'creatorusername': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'customdisplayview': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'damper': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'department': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'directmail': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'directoriespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'displayname': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'dob': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'dunsno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'education': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'email': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'email2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'entityid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'entityownerid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'exported': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'fancyhits': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'firstname': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'firstresponder': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'forumspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'functionaltitleid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'guid': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'hideaddress': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'hideemail': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'hideinsearch': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'hidephone': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'historicalmemberid': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'hits': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'homephone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'icon': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'initials': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'interactive': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'jobspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lang': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'lastlogon': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'lastname': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'lastupdatedatetime': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'loginname': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'mailingname': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'memberid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'membershipspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mobilephone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'newsletterpermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'openid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'owneruserid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'owneruserid2': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ownerusername': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'pager': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'phone2': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'plid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'positionassignment': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'positiontitle': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'referralsource': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'releasespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rememberlogin': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'resumespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'salutation': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True'}),
            'securitylevel': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'sessionid': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'sex': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'spouse': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'ssn': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'status': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'statusdetail': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'student': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'submitdate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'surveyspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'timezone': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'title': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'tscore': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tscoredatetime': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'url': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'url2': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'usergroupspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'userid': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'usertype': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'usertypeid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'workphone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'zipcode': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'})
        },
        'legacy.schipulemployee': {
            'Meta': {'object_name': 'SchipulEmployee', 'db_table': "u'schipulemployees'", 'managed': 'False'},
            'address': ('django.db.models.fields.CharField', [], {'max_length': '150', 'blank': 'True'}),
            'address2': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'addresstype': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'adminnotes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'agreedtotos': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'articlespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'author': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ballotspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'calendareventspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'catalogspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'company': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'contentmanagerspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'country': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'county': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'coursespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'createdatetime': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'creatoruserid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'creatorusername': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'customdisplayview': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'damper': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'department': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'directmail': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'directoriespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'displayname': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'dob': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'dunsno': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'education': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'email': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'email2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'entityid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'entityownerid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'exported': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'fancyhits': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'fax': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'firstname': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'firstresponder': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'forumspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'functionaltitleid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'guid': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'hideaddress': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'hideemail': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'hideinsearch': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'hidephone': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'historicalmemberid': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'hits': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'homephone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'icon': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'initials': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'interactive': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'jobspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lang': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'lastlogon': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'lastname': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'lastupdatedatetime': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'loginname': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'mailingname': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'memberid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'membershipspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'mobilephone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'newsletterpermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'openid': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'owneruserid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'owneruserid2': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'ownerusername': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'pager': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'phone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'phone2': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'plid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'positionassignment': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'positiontitle': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'referralsource': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'releasespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rememberlogin': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'}),
            'resumespermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'salutation': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True'}),
            'securitylevel': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'sessionid': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'sex': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'spouse': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'ssn': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'status': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'statusdetail': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'student': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'submitdate': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'surveyspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'timezone': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'title': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'tscore': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'tscoredatetime': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud1': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud2': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud3': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'ud4': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'url': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'url2': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'usergroupspermissions': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'userid': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'usertype': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'usertypeid': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'workphone': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'zipcode': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'})
        }
    }

    complete_apps = ['legacy']
