# Generated by Django 2.2.13 on 2020-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_auto_20200403_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdefault',
            name='reminder',
            field=models.BooleanField(default=True, verbose_name='Receive renewal reminders'),
        ),
    ]
