# Generated by Django 2.2.13 on 2020-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='enforce_direct_mail_flag',
            field=models.BooleanField(default=False, verbose_name="Skip members that have opted for Don't Send Email in their profile"),
        ),
    ]
