# Generated by Django 3.2.11 on 2022-02-15 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('newsletters', '0002_newsletter_enforce_direct_mail_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='repeats',
            field=models.IntegerField(blank=True, default=0, help_text='n = n times, -1 = forever', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Repeats'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='schedule_send_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starts On'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('O', 'Once'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='O', max_length=1, verbose_name='Frequency'),
        ),
        migrations.CreateModel(
            name='NewsletterRecurringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_email_sent', models.DateTimeField(blank=True, null=True)),
                ('email_sent_count', models.IntegerField(blank=True, default=0, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_data', to='newsletters.newsletter')),
            ],
        ),
    ]
