# Generated by Django 3.2.11 on 2022-02-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_auto_20220215_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletterrecurringdata',
            old_name='date_email_sent',
            new_name='finish_dt',
        ),
        migrations.AddField(
            model_name='newsletterrecurringdata',
            name='send_status',
            field=models.CharField(default='queued', max_length=30),
        ),
        migrations.AddField(
            model_name='newsletterrecurringdata',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
