# Generated by Django 2.2.14 on 2020-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['position'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AddField(
            model_name='region',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
    ]
