# Generated by Django 4.2.13 on 2024-07-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_entity_creator_alter_entity_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regions', '0003_auto_20200902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='tax_label_2',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Label for tax 2'),
        ),
        migrations.AddField(
            model_name='region',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Example: 0.0825 for 8.25%.', max_digits=6),
        ),
        migrations.AddField(
            model_name='region',
            name='tax_rate_2',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, help_text='Example: 0.0825 for 8.25%.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='region',
            name='creator',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='region',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_entity', to='entities.entity'),
        ),
        migrations.AlterField(
            model_name='region',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
