# Generated by Django 4.2.13 on 2024-07-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_region_tax_label_2_region_tax_rate_region_tax_rate_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='invoice_footer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='region',
            name='invoice_header',
            field=models.TextField(blank=True, default=''),
        ),
    ]
